name: 03-the-night-shift

on:
  schedule:
    - cron: '13 19 * * *'

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ETL script
        run: python etl/run.py